config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # get 'pets', to: 'pets#index'
  # get 'pets/new', to: 'pets#new'
  # get 'pets/:id', to: 'pets#show', as: :pet
  # post 'pets', to: 'pets#create'
  # get 'pets/:id/edit', to: 'pets#edit'
  # patch 'pets/:id', to: 'pets#update'
  # delete 'pets/:id', to: 'pets#destroy'

  resources :pets
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pet.rb
class Pet < ApplicationRecord
  SPECIES = ['cat', 'dog', 'turtle', 'rabbit', 'unicorn', 'turkey']
  validates :name, presence: true
  validates :species, inclusion: { in: SPECIES }

  def found_days_ago
    Time.now.day - self.found_on.day
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]

  def index
    @pets = Pet.all
  end

  def show
    @pet = Pet.find(params[:id])
  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)
    @pet.save

    redirect_to pets_path
  end

  def edit
  end

  def update
    @pet.update(pet_params)

    redirect_to pet_path(@pet)
  end

  def destroy
    @pet.destroy

    redirect_to pets_path
  end

  private

  def pet_params
    params.require(:pet).permit(:name, :address, :species, :found_on)
  end

  def set_pet
    @pet = Pet.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LostPets246</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pets/_form.html.erb
<%= simple_form_for pet do |f| %>
  <%= f.input :name, label: "Nom de l'animal", error: 'Username is mandatory, please specify one' %>
  <%= f.input :address, hint: 'No special characters.' %>
  <%= f.input :species, collection: Pet::SPECIES %>
  <%= f.input :found_on, as: :date, html5: true %>
  <%= f.button :submit %>
<% end %>

app/views/pets/edit.html.erb
<h3>Formulaire de modification</h3>

<%= render 'form', pet: @pet %>

<%= link_to 'Retour à la liste des animaux', pets_path %>

app/views/pets/index.html.erb
<h1>Tous les animaux disparus</h1>

<ul>
  <% @pets.each do |pet| %>
    <li>
      <p>
        <%= link_to pet.name, pet_path(pet) %> trouvé il y a <%= pet.found_days_ago %> jours
      </p>
    </li>
  <% end %>
</ul>

<%= link_to 'Déclarer un animal trouvé', new_pet_path, class: 'btn btn-success' %>

app/views/pets/new.html.erb
<h3>Formulaire de création</h3>

<%= render 'form', pet: @pet %>

<%= link_to 'Retour à la liste des animaux', pets_path %>

app/views/pets/show.html.erb
<h2><%= @pet.name %></h2>

<p>Trouvé au : <%= @pet.address %></p>
<p>Espèce : <%= @pet.species %></p>
<p>Trouvé le : <%= @pet.found_on %></p>

<%= link_to 'Modifier les infos', edit_pet_path(@pet) %>
<%= link_to "Supprimer l'animal", pet_path(@pet), method: :delete %>

<%= link_to 'Retour à la liste des animaux', pets_path %>